-- Dark Knight for Neovim: Omarchy's aether spec, plus the indent guides.
--
-- Generated by src/neovim.py from colors.toml and Omarchy's
-- default/themed/neovim.lua.tpl. Do not hand-edit: change the script.
--
-- Omarchy stages no .lua from a theme installed out of a git repo, so this
-- file applies where the theme is a local directory or a symlink to this
-- checkout. Installed from GitHub, the theme gets the template's spec.
return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      -- Decoration is not text. aether paints NonText and IblIndent from
      -- `muted`, which is also the comment colour, so every indent guide
      -- arrives at comment weight. These move the guides onto the theme's
      -- structure colour and the scope guides onto the dim accent; `muted`
      -- itself, and so every comment and line number, is left alone.
      on_highlights = function(hl)
        hl.NonText               = { fg = "#283943", nocombine = true } -- snacks links SnacksIndent here; also eol and extends
        hl.Whitespace            = { fg = "#283943", nocombine = true } -- listchars
        hl.IblIndent             = { fg = "#283943", nocombine = true } -- indent-blankline's own guide, painted from muted too
        hl.SnacksIndent          = { fg = "#283943", nocombine = true } -- set outright, so it cannot follow NonText elsewhere
        hl.SnacksIndentScope     = { fg = "#236A8C", nocombine = true } -- the scope guide: a marker, not a shout
        hl.SnacksIndentChunk     = { fg = "#236A8C", nocombine = true } -- same guide, chunk style
        hl.IblScope              = { fg = "#236A8C", nocombine = true } -- indent-blankline's scope guide, which is blue
        hl.MiniIndentscopeSymbol = { fg = "#236A8C", nocombine = true } -- mini.indentscope, if that is the one
      end,
      colors = {
        bg = "#0A1014",
        dark_bg = "#070B0D",
        darker_bg = "#040708",
        lighter_bg = "#162128",

        fg = "#CCCFD1",
        dark_fg = "#7F919C",
        light_fg = "#A1AAB0",
        bright_fg = "#ECEDEE",
        muted = "#5D7583",

        red = "#BF878C",
        yellow = "#A1966D",
        orange = "#B88D75",
        green = "#7B9F7E",
        cyan = "#5BA1A3",
        blue = "#8E93BC",
        magenta = "#B389A7",
        brown = "#755845",

        bright_red = "#E9AEB3",
        bright_yellow = "#C9BC92",
        bright_green = "#A1C6A4",
        bright_cyan = "#82C9CA",
        bright_blue = "#B4B9E4",
        bright_magenta = "#DAAFCE",

        accent = "#4F9EC9",
        cursor = "#ECEDEE",
        foreground = "#CCCFD1",
        background = "#0A1014",
        selection = "#0C2B3A",
        selection_foreground = "#ECEDEE",
        selection_background = "#0C2B3A",
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },
}
