-- Dark Knight for Neovim: Omarchy's aether spec, plus the indent guides
-- and a syntax pass that keeps hue for data.
--
-- Generated by src/neovim.py from colors.toml and Omarchy's
-- default/themed/neovim.lua.tpl. Do not hand-edit: change the script.
--
-- Omarchy stages no .lua from a theme installed out of a git repo, so this
-- file applies where the theme is a local directory or a symlink to this
-- checkout. Installed from GitHub, the theme gets the template's spec.
return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      -- Decoration is not text. aether paints NonText and IblIndent from
      -- `muted`, which is also the comment colour, so every indent guide
      -- arrives at comment weight. These move the guides onto the theme's
      -- structure colour and the scope guides onto the dim accent; `muted`
      -- itself, and so every comment and line number, is left alone.
      on_highlights = function(hl)
        hl.NonText               = { fg = "#283943", nocombine = true } -- snacks links SnacksIndent here; also eol and extends
        hl.Whitespace            = { fg = "#283943", nocombine = true } -- listchars
        hl.IblIndent             = { fg = "#283943", nocombine = true } -- indent-blankline's own guide, painted from muted too
        hl.SnacksIndent          = { fg = "#283943", nocombine = true } -- set outright, so it cannot follow NonText elsewhere
        hl.SnacksIndentScope     = { fg = "#596D7B", nocombine = true } -- the scope guide: a marker, not a shout
        hl.SnacksIndentChunk     = { fg = "#596D7B", nocombine = true } -- same guide, chunk style
        hl.IblScope              = { fg = "#596D7B", nocombine = true } -- indent-blankline's scope guide, which is blue
        hl.MiniIndentscopeSymbol = { fg = "#596D7B", nocombine = true } -- mini.indentscope, if that is the one

        -- Syntax: grammar on the grey ramp, names as text, definitions
        -- brightest, and hue only for data. See src/neovim.py.
        hl["Keyword"]                           = { fg = "#A1AAB0" } -- light_foreground
        hl["Statement"]                         = { fg = "#A1AAB0" } -- light_foreground
        hl["Conditional"]                       = { fg = "#A1AAB0" } -- light_foreground
        hl["Repeat"]                            = { fg = "#A1AAB0" } -- light_foreground
        hl["Exception"]                         = { fg = "#A1AAB0" } -- light_foreground
        hl["Define"]                            = { fg = "#A1AAB0" } -- light_foreground
        hl["Include"]                           = { fg = "#A1AAB0" } -- light_foreground
        hl["PreProc"]                           = { fg = "#A1AAB0" } -- light_foreground
        hl["@keyword"]                          = { fg = "#A1AAB0" } -- light_foreground
        hl["@keyword.function"]                 = { fg = "#A1AAB0" } -- light_foreground
        hl["Identifier"]                        = { fg = "#CCCFD1" } -- foreground
        hl["Function"]                          = { fg = "#CCCFD1" } -- foreground
        hl["@function.call"]                    = { fg = "#CCCFD1" } -- foreground
        hl["@function.method.call"]             = { fg = "#CCCFD1" } -- foreground
        hl["@property"]                         = { fg = "#CCCFD1" } -- foreground
        hl["@lsp.type.property"]                = { fg = "#CCCFD1" } -- foreground
        hl["@variable.member"]                  = { fg = "#CCCFD1" } -- foreground
        hl["@variable.parameter"]               = { fg = "#CCCFD1" } -- foreground
        hl["@string.documentation"]             = { fg = "#86969F" } -- dark_foreground
        hl["@function"]                         = { fg = "#ECEDEE", bold = true } -- bright_foreground
        hl["@function.method"]                  = { fg = "#ECEDEE", bold = true } -- bright_foreground
        hl["@lsp.typemod.function.declaration"] = { fg = "#ECEDEE", bold = true } -- bright_foreground
        hl["@lsp.typemod.method.declaration"]   = { fg = "#ECEDEE", bold = true } -- bright_foreground
        hl["Constant"]                          = { fg = "#B88D75" } -- orange
        hl["Type"]                              = { fg = "#99C1DC" } -- accent
        hl["StorageClass"]                      = { fg = "#99C1DC" } -- accent
        hl["Structure"]                         = { fg = "#99C1DC" } -- accent
        hl["Typedef"]                           = { fg = "#99C1DC" } -- accent
        hl["@constructor"]                      = { fg = "#99C1DC" } -- accent
      end,
      colors = {
        bg = "#0A1014",
        dark_bg = "#070B0D",
        darker_bg = "#040708",
        lighter_bg = "#162128",

        fg = "#CCCFD1",
        dark_fg = "#86969F",
        light_fg = "#A1AAB0",
        bright_fg = "#ECEDEE",
        muted = "#687F8D",

        red = "#BF878C",
        yellow = "#A1966D",
        orange = "#B88D75",
        green = "#7B9F7E",
        cyan = "#5BA1A3",
        blue = "#7F97BE",
        magenta = "#B389A7",
        brown = "#755845",

        bright_red = "#E9AEB3",
        bright_yellow = "#C9BC92",
        bright_green = "#A1C6A4",
        bright_cyan = "#82C9CA",
        bright_blue = "#A4BDE5",
        bright_magenta = "#DAAFCE",

        accent = "#99C1DC",
        cursor = "#ECEDEE",
        foreground = "#CCCFD1",
        background = "#0A1014",
        selection = "#222E36",
        selection_foreground = "#ECEDEE",
        selection_background = "#222E36",
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },
}
