#!/usr/bin/env python3
"""Emit btop.theme: the monitor on the theme's one hue.

    python3 src/btop.py > btop.theme

Omarchy's btop.theme.tpl gives each box its own ANSI hue (magenta, green, red)
and runs every meter through three more, which under this palette is a rainbow
at one loudness: the busiest window on the desktop in a theme whose rule is one
hue carried by light. Here a meter is a ramp of lightness, from steel up to
the accent and on to the brightest text, so a fuller bar is a lighter bar.
Hue is kept for the one reading where it means something: temperature, and
the top of a meter that is running out (memory used, CPU pinned), which ends
in the palette's orange and red.
"""

import pathlib
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent


def main():
    p = tomllib.load(open(ROOT / "colors.toml", "rb"))
    calm = ("accent_dim", "accent", "bright_foreground")
    warn = ("accent_dim", "accent", "orange")
    rows = [
        ("main_bg", "background"), ("main_fg", "foreground"),
        ("title", "bright_foreground"), ("hi_fg", "accent"),
        ("selected_bg", "selection"), ("selected_fg", "bright_foreground"),
        ("inactive_fg", "muted"), ("graph_text", "light_foreground"),
        ("meter_bg", "lighter_background"), ("proc_misc", "light_foreground"),
        ("cpu_box", "line"), ("mem_box", "line"), ("net_box", "line"),
        ("proc_box", "line"), ("div_line", "line"),
        ("temp_start", "green"), ("temp_mid", "yellow"), ("temp_end", "red"),
    ]
    for meter, ramp in (("cpu", warn), ("free", calm), ("cached", calm),
                        ("available", calm), ("used", warn),
                        ("download", calm), ("upload", calm),
                        ("process", warn)):
        rows += [(f"{meter}_{part}", key)
                 for part, key in zip(("start", "mid", "end"), ramp)]
    rows += [(f"gradient_color_{i}", key) for i, key in enumerate(
        ("background", "lighter_background", "selection", "line", "accent_dim",
         "muted", "accent", "bright_foreground"))]
    sys.stdout.write("# Generated by src/btop.py from colors.toml. Do not hand-edit.\n")
    for name, key in rows:
        sys.stdout.write(f'theme[{name}]="{p[key]}"\n')


if __name__ == "__main__":
    main()
