#!/usr/bin/env python3
"""Emit shell.controls.toml, the one shell section this theme overrides.

    python3 src/controls.py > shell.controls.toml

Omarchy generates shell.toml from colors.toml, and its `[controls]` defaults
make focus a mirror of hover: both plain foreground, so tab focus and the
selected row are indistinguishable from ordinary text. The template says so
itself and invites the override.

Why a section file rather than a whole shell.toml. A theme may ship either.
Shipping shell.toml freezes all 237 lines against future Omarchy changes;
shipping shell.<section>.toml replaces just that section, which is a freeze of
about thirty lines in the one section a theme is meant to own. It is still a
freeze: Omarchy replaces the whole section rather than merging key by key, so
a key added to `[controls]` upstream will not appear here until this file is
updated. That is the smallest available cost.

The values come from colors.toml, so the accent here cannot drift from the
accent everywhere else. That drift is real: shell.toml was hand-patched twice
during the 2026-09-04 rebuild and was stale both times the palette moved.

The rule the numbers express: the accent means here. Hover is transient and
stays steel; focus and the selected row are where you are, and take the
accent, focus outlined and selection filled so the two are still telling you
different things.
"""

import pathlib
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent


def main():
    p = tomllib.load(open(ROOT / "colors.toml", "rb"))
    fg, accent = p["foreground"], p["accent"]
    w = sys.stdout.write
    w("# Generated by src/controls.py from colors.toml. Do not hand-edit.\n")
    w("[controls]\n")
    w("# Idle control chrome.\n")
    w(f'normal-color        = "{fg}"\n')
    w("normal-fill-alpha   = 0.04\n")
    w(f'normal-border       = "{fg}"\n')
    w("normal-border-width = 1\n")
    w("normal-border-alpha = 0.4\n\n")
    w("# Hover and the panel keyboard cursor: transient, so steel.\n")
    w(f'hover-cursor-color        = "{fg}"\n')
    w("hover-cursor-fill-alpha   = 0.08\n")
    w(f'hover-cursor-border       = "{fg}"\n')
    w("hover-cursor-border-width = 1\n")
    w("hover-cursor-border-alpha = 0.25\n\n")
    w("# Focus: where you are. The accent, outlined.\n")
    w(f'focus-color        = "{accent}"\n')
    w("focus-fill-alpha   = 0.10\n")
    w(f'focus-border       = "{accent}"\n')
    w("focus-border-width = 1\n")
    w("focus-border-alpha = 0.45\n\n")
    w("# Selected: what you chose. The accent, filled rather than outlined, so\n")
    w("# focus and selection are still saying two different things.\n")
    w(f'selected-color        = "{accent}"\n')
    w("selected-fill-alpha   = 0.16\n")
    w(f'selected-border       = "{accent}"\n')
    w("selected-border-width = 0\n")
    w("selected-border-alpha = 1.0\n\n")
    w("# Momentary fills.\n")
    w("pressed-fill-alpha   = 0.22\n")
    w("selection-fill-alpha = 0.35\n")


if __name__ == "__main__":
    main()
