#!/usr/bin/env python3
"""Emit the shell sections this theme overrides, one file per section.

    python3 src/controls.py controls > shell.controls.toml
    python3 src/controls.py bar      > shell.bar.toml
    python3 src/controls.py launcher > shell.launcher.toml
    python3 src/controls.py menu     > shell.menu.toml
    python3 src/controls.py lock     > shell.lock.toml

Omarchy generates shell.toml from colors.toml, and its `[controls]` defaults
make focus a mirror of hover: both plain foreground, so tab focus and the
selected row are indistinguishable from ordinary text. The template says so
itself and invites the override.

Why a section file rather than a whole shell.toml. A theme may ship either.
Shipping shell.toml freezes all 237 lines against future Omarchy changes;
shipping shell.<section>.toml replaces just that section, which is a freeze of
about thirty lines in the one section a theme is meant to own. It is still a
freeze: Omarchy replaces the whole section rather than merging key by key, so
a key added to `[controls]` upstream will not appear here until this file is
updated. That is the smallest available cost.

The values come from colors.toml, so the accent here cannot drift from the
accent everywhere else. That drift is real: shell.toml was hand-patched twice
during the 2026-09-04 rebuild and was stale both times the palette moved.

The rule the numbers express: the accent means here. Hover is transient and
stays steel; focus and the selected row are where you are, and take the
accent, focus outlined and selection filled so the two are still telling you
different things.

bar, launcher and menu were written by hand on 2026-09-17 with the palette's
hexes typed into them, which is the drift described above waiting to happen a
third time, so they are generated here too. What they say: the bar and the two
pickers are slightly translucent over the wallpaper (the theme sets no blur of
its own; whether anything blurs behind them is the machine's Hyprland config),
and the selected row is a steel fill with accent text. The pickers' frame is the active window border, by
reference rather than by hex: it is what notifications, flyouts, tooltips and
the polkit card already wear, and an open menu is the focused thing on the
screen. The hand-written files framed them in `line` instead, which left the
desktop with two kinds of frame for one kind of surface. The bar's active workspace is `red`, the
one warm mark on the desktop, because it is the one thing on the bar that is
looked for rather than read.
"""

import pathlib
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent


HEAD = "# Generated by src/controls.py from colors.toml. Do not hand-edit.\n"


def bar(p, w):
    w(HEAD)
    w("# Status bar: slightly translucent over the wallpaper.\n")
    w("[bar]\n")
    w(f'background       = "{p["background"]}"\n')
    w("background-alpha = 0.88\n")
    w(f'text             = "{p["foreground"]}"\n')
    w(f'active           = "{p["red"]}"\n')
    w("scale-with-font  = true\n")
    w("size-horizontal  = 26\n")
    w("size-vertical    = 28\n")


def picker(section, p, w):
    """launcher and menu: the same surface, and one key apart upstream."""
    w(HEAD)
    w(f"# {section.capitalize()}: quiet frame, steel fill on the selected row.\n")
    w(f"[{section}]\n")
    w(f'background                = "{p["background"]}"\n')
    w("background-alpha          = 0.93\n")
    w(f'text                      = "{p["foreground"]}"\n')
    w('border                    = "hyprland.active-border-foreground"\n')
    w("border-alpha              = 1.0\n")
    w(f'scrim                     = "{p["background"]}"\n')
    w("scrim-alpha               = 0.5\n")
    w(f'selected-background       = "{p["selection"]}"\n')
    w("selected-background-alpha = 0.60\n")
    w(f'selected-text             = "{p["accent"]}"\n')
    w(f'selected-border           = "{p["selection"]}"\n')
    w("selected-border-alpha     = 0.0\n")
    if section == "launcher":
        w("selected-border-width     = 0\n")


def lock(p, w):
    """The lock screen's input card. Its backdrop is not a theme's to set:
    Omarchy blurs whatever the current wallpaper is until it is a soft field.

    Two changes from the generated section. The placeholder is `muted`, on the
    ramp, where the template mixes foreground into background and lands on a
    neutral grey that belongs to no step of this theme. And idle and typing
    are told apart: the template gives both the active border, so the card
    looks the same whether or not it has the keyboard's attention; here it
    rests on the dim accent and lights to the active border when you type.
    """
    w(HEAD)
    w("[lock]\n")
    w(f'background       = "{p["background"]}"\n')
    w("background-alpha = 0.8\n")
    w(f'text             = "{p["foreground"]}"\n')
    w(f'placeholder      = "{p["muted"]}"\n')
    w(f'text-error       = "{p["red"]}"\n')
    w(f'border           = "{p["accent_dim"]}"\n')
    w('border-active    = "hyprland.active-border"\n')
    w(f'border-error     = "{p["red"]}"\n')
    w("border-alpha     = 1.0\n")
    w(f'selection        = "{p["accent"]}"\n')
    w("selection-alpha  = 0.45\n")


def controls(p, w):
    fg, accent = p["foreground"], p["accent"]
    w(HEAD)
    w("[controls]\n")
    w("# Idle control chrome.\n")
    w(f'normal-color        = "{fg}"\n')
    w("normal-fill-alpha   = 0.04\n")
    w(f'normal-border       = "{fg}"\n')
    w("normal-border-width = 1\n")
    w("normal-border-alpha = 0.4\n\n")
    w("# Hover and the panel keyboard cursor: transient, so steel.\n")
    w(f'hover-cursor-color        = "{fg}"\n')
    w("hover-cursor-fill-alpha   = 0.08\n")
    w(f'hover-cursor-border       = "{fg}"\n')
    w("hover-cursor-border-width = 1\n")
    w("hover-cursor-border-alpha = 0.25\n\n")
    w("# Focus: where you are. The accent, outlined.\n")
    w(f'focus-color        = "{accent}"\n')
    w("focus-fill-alpha   = 0.10\n")
    w(f'focus-border       = "{accent}"\n')
    w("focus-border-width = 1\n")
    w("focus-border-alpha = 0.45\n\n")
    w("# Selected: what you chose. The accent, filled rather than outlined, so\n")
    w("# focus and selection are still saying two different things.\n")
    w(f'selected-color        = "{accent}"\n')
    w("selected-fill-alpha   = 0.16\n")
    w(f'selected-border       = "{accent}"\n')
    w("selected-border-width = 0\n")
    w("selected-border-alpha = 1.0\n\n")
    w("# Momentary fills.\n")
    w("pressed-fill-alpha   = 0.22\n")
    w("selection-fill-alpha = 0.35\n")


SECTIONS = ("controls", "bar", "launcher", "menu", "lock")


def main():
    if len(sys.argv) != 2 or sys.argv[1] not in SECTIONS:
        raise SystemExit("usage: controls.py " + "|".join(SECTIONS))
    p = tomllib.load(open(ROOT / "colors.toml", "rb"))
    section, w = sys.argv[1], sys.stdout.write
    if section == "controls":
        controls(p, w)
    elif section == "bar":
        bar(p, w)
    elif section == "lock":
        lock(p, w)
    else:
        picker(section, p, w)


if __name__ == "__main__":
    main()
