#!/usr/bin/env python3
"""Emit gtk.css from colors.toml.

    python3 src/gtk.py        > gtk.css     (GTK4 / libadwaita)
    python3 src/gtk.py --gtk3 > gtk3.css    (GTK3)

Omarchy generates seventeen surfaces from colors.toml and GTK is not one of
them: `omarchy-theme-set-gnome` only switches Adwaita between light and dark
and sets the icon theme. So without this file every GTK application falls back
to stock Adwaita-dark, which on this desktop means Nautilus, its previewer and
the file-chooser portal, together the fourth most focused thing here.

libadwaita reads a small set of named colours and derives the rest. Naming all
of them explicitly, rather than only the accent, is what stops a stock blue
turning up in a selection highlight or a link.

GTK3 needs its own file. It is still here: `xdg-desktop-portal-gtk` draws the
file chooser that every application opens, and it was the one surface still
wearing stock Adwaita after the GTK4 file landed. It cannot simply be given the
same file, because `alertdialog`, `banner`, `toast` and `menubutton` are GTK4
element names and a stylesheet GTK3 fails to parse applies nothing at all. So
`--gtk3` emits the colours, which are the part GTK3 actually reads, plus only
rules whose selectors exist there.

The mapping follows the theme's own ramp rather than flattening everything to
one background, which is what makes depth read correctly: the window is the
base, the file view is recessed below it, sidebars, cards and popovers are
raised above it, and borders are the ramp's own line colour instead of
translucent foreground.
"""

import pathlib
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent


def main():
    gtk3 = "--gtk3" in sys.argv[1:]
    p = tomllib.load(open(ROOT / "colors.toml", "rb"))
    w = sys.stdout.write

    w("/* Generated by src/gtk.py%s from colors.toml. Do not hand-edit. */\n\n"
      % (" --gtk3" if gtk3 else ""))

    w("/* The palette, by the names GTK applications reach for. */\n")
    for name, key in (
        ("background", "background"), ("foreground", "foreground"),
        ("black", "dark_background"), ("bright_black", "line"),
        ("red", "red"), ("green", "green"), ("yellow", "yellow"),
        ("blue", "blue"), ("magenta", "magenta"), ("cyan", "cyan"),
        ("white", "foreground"),
        ("bright_red", "bright_red"), ("bright_green", "bright_green"),
        ("bright_yellow", "bright_yellow"), ("bright_blue", "bright_blue"),
        ("bright_magenta", "bright_magenta"), ("bright_cyan", "bright_cyan"),
        ("bright_white", "bright_foreground"),
        ("accent", "accent"), ("accent_dim", "accent_dim"),
        ("surface", "lighter_background"), ("recessed", "dark_background"),
        ("line", "line"), ("muted", "muted"), ("dim", "dark_foreground"),
    ):
        w(f"@define-color {name:15} {p[key]};\n")

    if gtk3:
        w("""
/* GTK3 reads these names and derives the rest. */
@define-color theme_fg_color @foreground;
@define-color theme_text_color @foreground;
@define-color theme_bg_color @background;
@define-color theme_base_color @recessed;
@define-color theme_selected_bg_color @accent_dim;
@define-color theme_selected_fg_color @bright_white;
@define-color insensitive_bg_color @background;
@define-color insensitive_fg_color @muted;
@define-color insensitive_base_color @recessed;
@define-color theme_unfocused_fg_color @dim;
@define-color theme_unfocused_text_color @dim;
@define-color theme_unfocused_bg_color @background;
@define-color theme_unfocused_base_color @recessed;
@define-color theme_unfocused_selected_bg_color @accent_dim;
@define-color theme_unfocused_selected_fg_color @bright_white;
@define-color unfocused_insensitive_color @muted;
@define-color borders @line;
@define-color unfocused_borders @line;
@define-color content_view_bg @recessed;
@define-color text_view_bg @recessed;
@define-color warning_color @yellow;
@define-color error_color @red;
@define-color success_color @green;
@define-color destructive_color @red;
@define-color wm_bg @background;
@define-color wm_border_focused @accent;
@define-color wm_border_unfocused @line;

/* Square, to match the desktop. Circular controls stay circular. */
* {
    border-radius: 0;
}

.circular,
button.circular {
    border-radius: 9999px;
}

/* Explicit rules for every surface, because the named colours above reach
   almost nothing on their own.

   Adwaita-dark declares `@define-color theme_bg_color #353535` and then writes
   `#353535` as a literal in the rule that uses it, so redefining the name
   changes no pixel. Verified by extracting its own stylesheet out of libgtk-3
   (`/org/gtk/libgtk/theme/Adwaita/gtk-contained-dark.css`, 2039 lines):
   `.background` is `background-color: #353535`, `.view` is `#2d2d2d`,
   `headerbar` is a `#1b1b1b` gradient. The first version of this file defined
   the names and wrote one rule for the sidebar, and the sidebar was the only
   thing that changed.

   The selectors below are Adwaita's own, and the literals they replace are its
   nine most-used, which between them are every surface of a file chooser. This
   is not a whole GTK3 theme: it recolours the widgets that appear here. The
   ecosystem's complete answer is adw-gtk3, which is a full port built to read
   libadwaita's names; it is not used because Omarchy's theme-set forces
   gtk-theme back to Adwaita-dark on every apply, so it would revert. */

/* Windows and dialogs: Adwaita #353535. */
window,
dialog,
.background,
messagedialog .titlebar {
    background-color: @background;
    color: @foreground;
}

/* Header bars: Adwaita's #1b1b1b gradient. background-image: none, or the
   gradient survives the background-color and the bar stays grey. */
headerbar,
headerbar:backdrop,
.titlebar,
.titlebar:backdrop {
    background-image: none;
    background-color: @background;
    color: @foreground;
    border-color: @line;
    box-shadow: none;
}

/* Views: lists, trees, icon views, text views. Adwaita #2d2d2d. */
.view,
iconview,
.view text,
iconview text,
textview text,
treeview.view,
list,
list row,
scrolledwindow viewport {
    background-color: @recessed;
    color: @foreground;
}

/* The sidebar, raised above the list it sits beside. */
.sidebar,
placessidebar,
placessidebar list,
placessidebar row,
.sidebar list {
    background-color: @surface;
    color: @foreground;
}

/* Buttons: Adwaita paints a gradient and a border. */
button,
button:backdrop {
    background-image: none;
    background-color: @surface;
    color: @foreground;
    border-color: @line;
    text-shadow: none;
    box-shadow: none;
}

button:hover {
    background-color: @line;
}

button:active,
button:checked {
    background-color: @accent_dim;
    color: @bright_white;
}

button:disabled {
    background-color: @recessed;
    color: @muted;
}

button.suggested-action {
    background-color: @accent_dim;
    color: @bright_white;
    border-color: @accent_dim;
}

button.destructive-action {
    background-color: @red;
    color: @background;
    border-color: @red;
}

/* The action classes sit at the same specificity as button:disabled and come
   after it, so without these a disabled Select or Open button keeps its
   enabled colours and hover feedback disappears. The file chooser's own
   confirm button is a suggested-action, so this is the one that mattered. */
button.suggested-action:hover {
    background-color: @accent;
    color: @background;
}

button.destructive-action:hover {
    background-color: @bright_red;
    color: @background;
}

button.suggested-action:disabled,
button.destructive-action:disabled {
    background-color: @recessed;
    color: @muted;
    border-color: @line;
}

/* Entries, including the file chooser's search and location bars. */
entry,
entry:backdrop,
spinbutton:not(.vertical) {
    background-image: none;
    background-color: @recessed;
    color: @foreground;
    border-color: @line;
    box-shadow: none;
}

entry:focus {
    border-color: @accent;
}

/* Selection: Adwaita #15539e. */
selection,
:selected,
:selected:focus,
.view:selected,
list row:selected,
treeview.view:selected,
placessidebar row:selected {
    background-color: @accent_dim;
    color: @bright_white;
}

/* Structure: Adwaita's #070707 borders and its separators. */
/* background-image: none, because Adwaita paints the pane divider as
   `image(#1b1b1b)` rather than as a colour, and an image sits above whatever
   background-color is set underneath it. */
separator,
.separator,
paned > separator {
    background-image: none;
    background-color: @line;
    color: @line;
}

scrollbar,
scrollbar:backdrop {
    background-color: @background;
    border-color: @line;
}

scrollbar slider {
    background-color: @muted;
}

scrollbar slider:hover {
    background-color: @dim;
}

/* Links and anything Adwaita paints in its own accent. */
*:link,
label:link {
    color: @accent;
}

/* A link inside a selected row would otherwise be the accent on the dim
   accent, which measures 2.01:1 and is unreadable. */
:selected *:link,
:selected label:link,
*:link:selected {
    color: @bright_white;
}

/* Tooltips. */
tooltip,
tooltip.background {
    background-color: @surface;
    color: @foreground;
    border: 1px solid @line;
}

/* The file chooser's own chrome. */
filechooser .dialog-action-box,
filechooser #pathbarbox {
    border-color: @line;
}

filechooser .dialog-action-box:backdrop,
filechooser #pathbarbox:backdrop {
    border-color: @recessed;
}
""")
        return

    w("""
/* libadwaita's semantic names, all of them, so no stock blue survives
   anywhere.

   Two accents, because a filled selection and a coloured word are not the same
   job. The full accent on a sidebar row was the loudest thing in the window: a
   row is a large filled area and the accent is the theme's most chromatic
   colour. Fills take the dim accent; text, links and icons keep the full one,
   where a few pixels of colour is the point. */
@define-color accent_bg_color @accent_dim;
@define-color accent_fg_color @bright_white;
@define-color accent_color @accent;

/* Depth, on the theme's own ramp. Flattening these to one colour is what makes
   a dark GTK app read as a single sheet with no structure. */
@define-color window_bg_color @background;
@define-color window_fg_color @foreground;
@define-color view_bg_color @recessed;
@define-color view_fg_color @foreground;
/* The sidebar is raised, not recessed. At the same near-black as the file list
   there was no edge between them at all and the window read as one sheet. */
@define-color sidebar_bg_color @surface;
@define-color sidebar_fg_color @foreground;
@define-color sidebar_backdrop_color @recessed;
@define-color sidebar_shade_color @recessed;
@define-color headerbar_bg_color @background;
@define-color headerbar_fg_color @foreground;
@define-color headerbar_backdrop_color @recessed;
@define-color headerbar_shade_color @recessed;
@define-color card_bg_color @surface;
@define-color card_fg_color @foreground;
@define-color popover_bg_color @surface;
@define-color popover_fg_color @foreground;
@define-color dialog_bg_color @surface;
@define-color dialog_fg_color @foreground;
@define-color thumbnail_bg_color @surface;
@define-color thumbnail_fg_color @foreground;

/* State. Destructive and error share red deliberately: a palette with two
   different reds for "this will delete something" and "this went wrong"
   teaches nothing and looks like a mistake. */
@define-color destructive_bg_color @red;
@define-color destructive_fg_color @background;
@define-color destructive_color @red;
@define-color error_bg_color @red;
@define-color error_fg_color @background;
@define-color error_color @red;
@define-color success_bg_color @green;
@define-color success_fg_color @background;
@define-color success_color @green;
@define-color warning_bg_color @yellow;
@define-color warning_fg_color @background;
@define-color warning_color @yellow;

/* Borders are the ramp's line colour, not translucent foreground: alpha over
   a dark ground gives a grey that belongs to no part of this palette. */
@define-color borders @line;
@define-color unfocused_borders @line;

/* The GTK3 names, for anything that has not moved to libadwaita. */
@define-color theme_fg_color @foreground;
@define-color theme_text_color @foreground;
@define-color theme_bg_color @background;
@define-color theme_base_color @recessed;
@define-color theme_selected_bg_color @accent_dim;
@define-color theme_selected_fg_color @bright_white;
@define-color insensitive_bg_color @background;
@define-color insensitive_fg_color @muted;
@define-color insensitive_base_color @recessed;
@define-color theme_unfocused_fg_color @dim;
@define-color theme_unfocused_text_color @dim;
@define-color theme_unfocused_bg_color @background;
@define-color theme_unfocused_base_color @recessed;
@define-color theme_unfocused_selected_bg_color @accent_dim;
@define-color theme_unfocused_selected_fg_color @bright_white;
@define-color unfocused_insensitive_color @muted;
@define-color content_view_bg @recessed;
@define-color text_view_bg @recessed;

/* Widgets libadwaita's named colours do not reach. */
messagedialog,
alertdialog.background {
    background-color: @dialog_bg_color;
    color: @dialog_fg_color;
}

messagedialog label,
alertdialog label {
    color: @dialog_fg_color;
}

messagedialog .secondary-text {
    color: @dim;
}

messagedialog button,
alertdialog button {
    background-color: @recessed;
    color: @foreground;
    border: 1px solid @line;
}

messagedialog button:hover,
alertdialog button:hover {
    background-color: @surface;
    border-color: @accent;
}

alertdialog .titlebar {
    background-color: @headerbar_bg_color;
    color: @headerbar_fg_color;
}

banner revealer widget {
    background: @surface;
    color: @foreground;
}

toast {
    background-color: @surface;
    color: @foreground;
}

/* The file chooser, which is the GTK surface seen most often here: it is the
   portal every application opens to pick a file. */
filechooser .dialog-action-box,
filechooser #pathbarbox {
    border-color: @line;
}

filechooser .dialog-action-box:backdrop,
filechooser #pathbarbox:backdrop {
    border-color: @recessed;
}

filechooserbutton:drop(active) {
    box-shadow: none;
    border-color: transparent;
}

/* Square, everywhere, to match the desktop. libadwaita rounds nearly every
   widget from its own stylesheet and Hyprland's rounding cannot reach inside a
   window, so a square desktop with rounded GTK dialogs, buttons and popovers
   would be the one place the decision did not hold.

   The blanket rule is deliberate rather than lazy: naming widgets one at a
   time leaves whichever one libadwaita adds next still rounded, which is the
   same drift this theme keeps fixing elsewhere. Circular controls are left
   alone, because a square avatar or a squared-off close button is not a
   sharper corner, it is a different widget. */
* {
    border-radius: 0;
}

.circular,
avatar,
button.circular,
.osd .circular,
/* The class sits on the wrapper and the child draws the control, so matching
   only .circular squares the button inside every circular menu button. */
menubutton.circular > button,
menubutton.circular > button.toggle,
.circular > button {
    border-radius: 9999px;
}

/* Selection, everywhere it appears. */
selection,
:selected {
    background-color: @accent_dim;
    color: @bright_white;
}
""")


if __name__ == "__main__":
    main()
