#!/usr/bin/env python3
"""Emit gtk.css from colors.toml.

    python3 src/gtk.py        > gtk.css     (GTK4 / libadwaita)
    python3 src/gtk.py --gtk3 > gtk3.css    (GTK3)

Omarchy generates seventeen surfaces from colors.toml and GTK is not one of
them: `omarchy-theme-set-gnome` only switches Adwaita between light and dark
and sets the icon theme. So without this file every GTK application falls back
to stock Adwaita-dark, which on this desktop means Nautilus, its previewer and
the file-chooser portal, together the fourth most focused thing here.

libadwaita reads a small set of named colours and derives the rest. Naming all
of them explicitly, rather than only the accent, is what stops a stock blue
turning up in a selection highlight or a link.

GTK3 needs its own file. It is still here: `xdg-desktop-portal-gtk` draws the
file chooser that every application opens, and it was the one surface still
wearing stock Adwaita after the GTK4 file landed. It cannot simply be given the
same file, because `alertdialog`, `banner`, `toast` and `menubutton` are GTK4
element names and a stylesheet GTK3 fails to parse applies nothing at all. So
`--gtk3` emits the colours, which are the part GTK3 actually reads, plus only
rules whose selectors exist there.

The mapping follows the theme's own ramp rather than flattening everything to
one background, which is what makes depth read correctly: the window is the
base, the file view is recessed below it, sidebars, cards and popovers are
raised above it, and borders are the ramp's own line colour instead of
translucent foreground.
"""

import pathlib
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent


def main():
    gtk3 = "--gtk3" in sys.argv[1:]
    p = tomllib.load(open(ROOT / "colors.toml", "rb"))
    w = sys.stdout.write

    w("/* Generated by src/gtk.py%s from colors.toml. Do not hand-edit. */\n\n"
      % (" --gtk3" if gtk3 else ""))

    w("/* The palette, by the names GTK applications reach for. */\n")
    for name, key in (
        ("background", "background"), ("foreground", "foreground"),
        ("black", "dark_background"), ("bright_black", "line"),
        ("red", "red"), ("green", "green"), ("yellow", "yellow"),
        ("blue", "blue"), ("magenta", "magenta"), ("cyan", "cyan"),
        ("white", "foreground"),
        ("bright_red", "bright_red"), ("bright_green", "bright_green"),
        ("bright_yellow", "bright_yellow"), ("bright_blue", "bright_blue"),
        ("bright_magenta", "bright_magenta"), ("bright_cyan", "bright_cyan"),
        ("bright_white", "bright_foreground"),
        ("accent", "accent"), ("accent_dim", "accent_dim"),
        ("surface", "lighter_background"), ("recessed", "dark_background"),
        ("line", "line"), ("muted", "muted"), ("dim", "dark_foreground"),
    ):
        w(f"@define-color {name:15} {p[key]};\n")

    if gtk3:
        w("""
/* GTK3 reads these names and derives the rest. */
@define-color theme_fg_color @foreground;
@define-color theme_text_color @foreground;
@define-color theme_bg_color @background;
@define-color theme_base_color @recessed;
@define-color theme_selected_bg_color @accent_dim;
@define-color theme_selected_fg_color @bright_white;
@define-color insensitive_bg_color @background;
@define-color insensitive_fg_color @muted;
@define-color insensitive_base_color @recessed;
@define-color theme_unfocused_fg_color @dim;
@define-color theme_unfocused_text_color @dim;
@define-color theme_unfocused_bg_color @background;
@define-color theme_unfocused_base_color @recessed;
@define-color theme_unfocused_selected_bg_color @accent_dim;
@define-color theme_unfocused_selected_fg_color @bright_white;
@define-color unfocused_insensitive_color @muted;
@define-color borders @line;
@define-color unfocused_borders @line;
@define-color content_view_bg @recessed;
@define-color text_view_bg @recessed;
@define-color warning_color @yellow;
@define-color error_color @red;
@define-color success_color @green;
@define-color destructive_color @red;
@define-color wm_bg @background;
@define-color wm_border_focused @accent;
@define-color wm_border_unfocused @line;

/* Square, to match the desktop. Circular controls stay circular. */
* {
    border-radius: 0;
}

.circular,
button.circular {
    border-radius: 9999px;
}

/* The file chooser: the GTK3 surface still seen every day, because
   xdg-desktop-portal-gtk draws it for every application that opens a file. */
filechooser .dialog-action-box,
filechooser #pathbarbox {
    border-color: @line;
}

filechooser .dialog-action-box:backdrop,
filechooser #pathbarbox:backdrop {
    border-color: @recessed;
}

.sidebar,
placessidebar,
placessidebar list {
    background-color: @surface;
    color: @foreground;
}

selection,
:selected {
    background-color: @accent_dim;
    color: @bright_white;
}
""")
        return

    w("""
/* libadwaita's semantic names, all of them, so no stock blue survives
   anywhere.

   Two accents, because a filled selection and a coloured word are not the same
   job. The full accent on a sidebar row was the loudest thing in the window: a
   row is a large filled area and the accent is the theme's most chromatic
   colour. Fills take the dim accent; text, links and icons keep the full one,
   where a few pixels of colour is the point. */
@define-color accent_bg_color @accent_dim;
@define-color accent_fg_color @bright_white;
@define-color accent_color @accent;

/* Depth, on the theme's own ramp. Flattening these to one colour is what makes
   a dark GTK app read as a single sheet with no structure. */
@define-color window_bg_color @background;
@define-color window_fg_color @foreground;
@define-color view_bg_color @recessed;
@define-color view_fg_color @foreground;
/* The sidebar is raised, not recessed. At the same near-black as the file list
   there was no edge between them at all and the window read as one sheet. */
@define-color sidebar_bg_color @surface;
@define-color sidebar_fg_color @foreground;
@define-color sidebar_backdrop_color @recessed;
@define-color sidebar_shade_color @recessed;
@define-color headerbar_bg_color @background;
@define-color headerbar_fg_color @foreground;
@define-color headerbar_backdrop_color @recessed;
@define-color headerbar_shade_color @recessed;
@define-color card_bg_color @surface;
@define-color card_fg_color @foreground;
@define-color popover_bg_color @surface;
@define-color popover_fg_color @foreground;
@define-color dialog_bg_color @surface;
@define-color dialog_fg_color @foreground;
@define-color thumbnail_bg_color @surface;
@define-color thumbnail_fg_color @foreground;

/* State. Destructive and error share red deliberately: a palette with two
   different reds for "this will delete something" and "this went wrong"
   teaches nothing and looks like a mistake. */
@define-color destructive_bg_color @red;
@define-color destructive_fg_color @background;
@define-color destructive_color @red;
@define-color error_bg_color @red;
@define-color error_fg_color @background;
@define-color error_color @red;
@define-color success_bg_color @green;
@define-color success_fg_color @background;
@define-color success_color @green;
@define-color warning_bg_color @yellow;
@define-color warning_fg_color @background;
@define-color warning_color @yellow;

/* Borders are the ramp's line colour, not translucent foreground: alpha over
   a dark ground gives a grey that belongs to no part of this palette. */
@define-color borders @line;
@define-color unfocused_borders @line;

/* The GTK3 names, for anything that has not moved to libadwaita. */
@define-color theme_fg_color @foreground;
@define-color theme_text_color @foreground;
@define-color theme_bg_color @background;
@define-color theme_base_color @recessed;
@define-color theme_selected_bg_color @accent_dim;
@define-color theme_selected_fg_color @bright_white;
@define-color insensitive_bg_color @background;
@define-color insensitive_fg_color @muted;
@define-color insensitive_base_color @recessed;
@define-color theme_unfocused_fg_color @dim;
@define-color theme_unfocused_text_color @dim;
@define-color theme_unfocused_bg_color @background;
@define-color theme_unfocused_base_color @recessed;
@define-color theme_unfocused_selected_bg_color @accent_dim;
@define-color theme_unfocused_selected_fg_color @bright_white;
@define-color unfocused_insensitive_color @muted;
@define-color content_view_bg @recessed;
@define-color text_view_bg @recessed;

/* Widgets libadwaita's named colours do not reach. */
messagedialog,
alertdialog.background {
    background-color: @dialog_bg_color;
    color: @dialog_fg_color;
}

messagedialog label,
alertdialog label {
    color: @dialog_fg_color;
}

messagedialog .secondary-text {
    color: @dim;
}

messagedialog button,
alertdialog button {
    background-color: @recessed;
    color: @foreground;
    border: 1px solid @line;
}

messagedialog button:hover,
alertdialog button:hover {
    background-color: @surface;
    border-color: @accent;
}

alertdialog .titlebar {
    background-color: @headerbar_bg_color;
    color: @headerbar_fg_color;
}

banner revealer widget {
    background: @surface;
    color: @foreground;
}

toast {
    background-color: @surface;
    color: @foreground;
}

/* The file chooser, which is the GTK surface seen most often here: it is the
   portal every application opens to pick a file. */
filechooser .dialog-action-box,
filechooser #pathbarbox {
    border-color: @line;
}

filechooser .dialog-action-box:backdrop,
filechooser #pathbarbox:backdrop {
    border-color: @recessed;
}

filechooserbutton:drop(active) {
    box-shadow: none;
    border-color: transparent;
}

/* Square, everywhere, to match the desktop. libadwaita rounds nearly every
   widget from its own stylesheet and Hyprland's rounding cannot reach inside a
   window, so a square desktop with rounded GTK dialogs, buttons and popovers
   would be the one place the decision did not hold.

   The blanket rule is deliberate rather than lazy: naming widgets one at a
   time leaves whichever one libadwaita adds next still rounded, which is the
   same drift this theme keeps fixing elsewhere. Circular controls are left
   alone, because a square avatar or a squared-off close button is not a
   sharper corner, it is a different widget. */
* {
    border-radius: 0;
}

.circular,
avatar,
button.circular,
.osd .circular,
/* The class sits on the wrapper and the child draws the control, so matching
   only .circular squares the button inside every circular menu button. */
menubutton.circular > button,
menubutton.circular > button.toggle,
.circular > button {
    border-radius: 9999px;
}

/* Selection, everywhere it appears. */
selection,
:selected {
    background-color: @accent_dim;
    color: @bright_white;
}
""")


if __name__ == "__main__":
    main()
